services:
  rpi-seism-daemon:
    build:
      context: ./daemon
      dockerfile: Dockerfile

    ports:
      - 8765:8765
    volumes:
      - ./data:/app/data  # Change ./data to the actual path of your data directory on the host ex: /home/user/rpi-seism/data/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0   # adjust to your port (ttyUSB0, ttyS0, etc.)
    group_add:
      - dialout                      # grants serial port access without root
    restart: unless-stopped

  rpi-seism-api:
    build:
      context: ./api
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    volumes:
      - ./data:/usr_data  # Change ./data to the actual path of your data directory on the host ex: /home/user/rpi-seism/data/
    restart: unless-stopped

  rpi-seism-web:
    build:
      context: ./web
      dockerfile: Dockerfile

    depends_on:
      - rpi-seism-api

    ports:
      - 3000:80
    restart: unless-stopped
